services:
  gatekeeper:
    container_name: gatekeeper_web
    ports:
      - '3001:3000'
    build:
      context: .
    environment:
      VITE_GATEKEEPER_URL: ${VITE_GATEKEEPER_URL}
      VITE_KRATOS_URL: ${VITE_KRATOS_URL}
      VITE_WEBSITE_URL: ${VITE_WEBSITE_URL}
      GK_TOKEN: ${GK_TOKEN}
    networks:
      - intranet

  postgres:
    container_name: gatekeeper_db
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - intranet

  migrate:
    container_name: gatekeeper_db_migrate
    build:
      context: prisma
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - intranet

networks:
  intranet:
    external: true

volumes:
  postgres: